---
# tasks file for vector-role
- name: install rpm
  become: true
  ansible.builtin.apt:
    name: "{{ vector_url }}"
    state: present
- name: create config
  become: true
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: /etc/vector/vector.yml
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
- name: create systemd unit
  become: true
  ansible.builtin.template:
    src: templates/vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
- name: VECTOR | Start service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true 